### ISSUE TITLE
Suggestion/fix: use license identifier

### ISSUE THREAD

**Issue by dunak-debug** [natuna-framework/fivem#6]
I suggest you to use license identifier instead of steam. 

Steam API and using it as identifier is considered as not reliable by CFX team.

**Comment by raflymln** [comment]
Sure! why not?

I'll plan to have the user determining which license they wanted as the second license, might be completed in 1-2 days later.

Thank you for your help 😀

**Comment by dunak-debug** [comment]
Yes, good idea making license default identifier as suggested by CFX and the other one being user configurable. Looking forward to your framework and if i would have more time in future i will contribute for sure!

**Comment by raflymln** [comment]
Fixed in 1.4.0
