### ISSUE TITLE
Suggestion: Menu builder

### ISSUE THREAD

**Issue by Mitroxs** [natuna-framework/fivem#7]
Would be cool to see some integrated Menu builder

Better description :

- Server side functions to "create" menus
- Some form of id attached to each "menu" created upon start, for temporarily disabling it or only giving certain "roles" permissions to access it .

**Comment by Mitroxs** [comment]
-PS would love to do it myself, but at the moment my TS capabilities are heavily limited so thought i would throw the suggestion out there incase someone wishes to make a pr with it :)

**Comment by raflymln** [comment]
Don't worry about that! I'm currently working on it :D

And like i say, i want to give it a maximum satisfaction, so there would be an upgrade to the ui as well as the code

preview
![](https://snipboard.io/yLKTzm.jpg)

**Comment by Mitroxs** [comment]
👍
